/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.controller.AfiliadoJpaController;
import com.controller.ComprobanteJpaController;
import com.controller.PlanJpaController;
import com.controller.ServicioJpaController;
import com.entities.Afiliado;
import com.entities.Comprobante;
import com.entities.Plan;
import com.entities.Servicio;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQUIPO
 */
public class crud_contratos extends javax.swing.JFrame {

    AfiliadoJpaController afiliadoCTR = new AfiliadoJpaController();
    Afiliado cliente = new Afiliado();

    ComprobanteJpaController comprobanteCtr = new ComprobanteJpaController();
    Comprobante comprobante = new Comprobante();

    ServicioJpaController servicioCtr = new ServicioJpaController();
    Servicio servicio = new Servicio();

    PlanJpaController planCtr = new PlanJpaController();
    Plan plan = new Plan();

    int costoTotal;

    DefaultTableModel modeloServicios;

    public crud_contratos() {
        initComponents();
        costoTotal = 0;
        crearTablaServiciosSelect();
        getTablaServicios();
        getComboBox();

    }

    private void crearTablaServiciosSelect() {

        String col[] = {"ID", "NOMBRE", "COPAGO", "COSTO"};
        modeloServicios = new DefaultTableModel(col, 0);
    }

    private void getComboBox() {
        List ls;
        ls = afiliadoCTR.findAfiliadoEntities();
        String value = "";
        for (int i = 0; i < ls.size(); i++) {
            cliente = (Afiliado) ls.get(i);
            value = cliente.getCodigo() + " " + cliente.getNombre();
            cbCLiente.addItem(value);
        }
    }

    private void getTablaServicios() {
        String col[] = {"ID", "NOMBRE", "COPAGO", "COSTO"};
        DefaultTableModel modelo = new DefaultTableModel(col, 0);
        Object obj[] = new Object[5];
        List ls;
        try {
            ls = servicioCtr.findServicioEntities();
            for (int i = 0; i < ls.size(); i++) {
                servicio = (Servicio) ls.get(i);
                obj[0] = servicio.getCodigo();
                obj[1] = servicio.getNombre();
                obj[2] = servicio.getCopago();
                obj[3] = servicio.getCostoEnPlan();
                modelo.addRow(obj);
            }
            this.jTableServiciosC.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar persistencia");

        }

    }

    private void addServicioAPlan(Servicio servicioAux) {
        Object obj[] = new Object[5];
        try {

            obj[0] = servicioAux.getCodigo();
            obj[1] = servicioAux.getNombre();
            obj[2] = servicioAux.getCopago();
            obj[3] = servicioAux.getCostoEnPlan();
            modeloServicios.addRow(obj);

            this.jTableSeleccionado.setModel(modeloServicios);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar persistencia");

        }

    }

    private void setearComprobante() {

        String[] newString = cbCLiente.getSelectedItem().toString().split("\\s+");
        int idAfiliado = Integer.parseInt(newString[0]);
        comprobante.setIdAfiliado(afiliadoCTR.findAfiliado(idAfiliado));
        comprobante.setMedioDePago(cbMEDIOPAGO.getSelectedItem().toString());
        comprobante.setIdPlan(plan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbCLiente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_codigoPlan = new javax.swing.JTextField();
        cbMEDIOPAGO = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnGenerarComprobante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServiciosC = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSeleccionado = new javax.swing.JTable();
        btnElegirServicio = new javax.swing.JButton();
        btnCrearPlan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("CODIGO CLIENTE:");

        cbCLiente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un cliente" }));

        jLabel2.setText("CODIGO PLAN");

        txt_codigoPlan.setEnabled(false);

        cbMEDIOPAGO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UN MEDIO DE PAGO", "CUENTA CORRIENTE", "CUENTA AHORRO", "TARJETA DE CREDITO", "PAGO EFECTIVO" }));

        jLabel3.setText("MEDIO DE PAGO:");

        btnGenerarComprobante.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnGenerarComprobante.setText("GENERAR COMPROBANTE ");
        btnGenerarComprobante.setEnabled(false);
        btnGenerarComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarComprobanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbMEDIOPAGO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(251, 251, 251)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(btnGenerarComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_codigoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_codigoPlan)
                            .addComponent(cbCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGenerarComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbMEDIOPAGO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTableServiciosC.setBackground(new java.awt.Color(204, 204, 255));
        jTableServiciosC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableServiciosC);

        jTableSeleccionado.setBackground(new java.awt.Color(204, 255, 204));
        jTableSeleccionado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSeleccionado);

        btnElegirServicio.setText("ELEGIR ->");
        btnElegirServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirServicioActionPerformed(evt);
            }
        });

        btnCrearPlan.setText("CREAR PLAN");
        btnCrearPlan.setEnabled(false);
        btnCrearPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnElegirServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrearPlan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnElegirServicio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnCrearPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarComprobanteActionPerformed

        try {
            setearComprobante();
            comprobanteCtr.create(comprobante);
            btnGenerarComprobante.setEnabled(false);
            btnElegirServicio.setEnabled(true);
            crearTablaServiciosSelect();
            this.jTableServiciosC.setModel(modeloServicios);
            JOptionPane.showMessageDialog(this, "Agregado con exito");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, "Error al insertar datos en la bd");
        }

    }//GEN-LAST:event_btnGenerarComprobanteActionPerformed

    private void btnElegirServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirServicioActionPerformed
        // TODO add your handling code here:

        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el codigo del servicio"));
        servicio = servicioCtr.findServicio(codigo);
        if (!plan.getServicioList().isEmpty()) {
            if (plan.getServicioList().contains(servicio)) {
                JOptionPane.showMessageDialog(null, "Ya ingresó este servicio");
            } else {
                plan.getServicioList().add(servicio);
                costoTotal += servicio.getCostoEnPlan();
                addServicioAPlan(servicio);

            }
        } else {
            plan.getServicioList().add(servicio);
            btnCrearPlan.setEnabled(true);
            costoTotal += servicio.getCostoEnPlan();
            addServicioAPlan(servicio);
        }
    }//GEN-LAST:event_btnElegirServicioActionPerformed

    private void btnCrearPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPlanActionPerformed
        // TODO add your handling code here:
        if (cbCLiente.getSelectedIndex() != 0) {
            try {
                String str = cbCLiente.getSelectedItem().toString();
                String[] newStr = str.split("\\s+");
                int codigoCliente = Integer.parseInt(newStr[0]);
                cliente = afiliadoCTR.findAfiliado(codigoCliente);
                if (!cliente.getComprobanteList().isEmpty()) {
                cbCLiente.setEnabled(false);
                plan.setNumeroBeneficiarios(cliente.getBeneficiarioList().size());
                List ls = planCtr.findPlanEntities();
                int codigoPlan = ls.size() + 1;
                plan.setCodigo(codigoPlan);
                txt_codigoPlan.setText(codigoPlan + "");
                
                    
                    JOptionPane.showMessageDialog(null, "El cliente ya tiene asignado un plan porfavor eliminelo para crear uno nuevo o modifiquelo");
                } else {
                    btnElegirServicio.setEnabled(false);
                    btnGenerarComprobante.setEnabled(true);
                    btnCrearPlan.setEnabled(false);
                    plan.setCostoTotal(costoTotal);
                    // planCtr.create(plan);
                    JOptionPane.showMessageDialog(null, "Plan creado");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");
        }
    }//GEN-LAST:event_btnCrearPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud_contratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud_contratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud_contratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud_contratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud_contratos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPlan;
    private javax.swing.JButton btnElegirServicio;
    private javax.swing.JButton btnGenerarComprobante;
    private javax.swing.JComboBox<String> cbCLiente;
    private javax.swing.JComboBox<String> cbMEDIOPAGO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSeleccionado;
    private javax.swing.JTable jTableServiciosC;
    private javax.swing.JTextField txt_codigoPlan;
    // End of variables declaration//GEN-END:variables
}
